version: '3'

services:
    caliper:
        container_name: caliper
        image: hyperledger/caliper:0.4.2
        command: launch manager
        environment:
          - CALIPER_BIND_SUT=besu:1.4
          - CALIPER_BENCHCONFIG=benchmarks/scenario/simple/config.yaml
          - CALIPER_NETWORKCONFIG=networks/4node-ibft2/networkconfig.json
        volumes:
          - ~/GitHub-WorkSpace/ubeta/caliper-benchmarks:/hyperledger/caliper/workspace