global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: 
      - localhost:9090
  - job_name: push-gateway-node-x
    metrics_path: /metrics
    honor_labels: true
    scheme: http
    static_configs:
    - targets:
      - 192.168.226.75:9091