global:
  scrape_interval: 15s
scrape_configs:
- job_name: prometheus
  static_configs:
  - targets:
    - localhost:9090
- honor_labels: true
  job_name: push-gateway-node-4-node-4
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 102.168.226.75:9091
