global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
    - targets: ["localhost:9090"]
  # - job_name: besu
  #   scrape_interval: 15s
  #   scrape_timeout: 10s
  #   metrics_path: /metrics
  #   scheme: http
  #   static_configs:
  #   - targets:
  #     - localhost:9545
  - job_name: push-gateway
    metrics_path: /metrics
    honor_labels: true
    scheme: http
    static_configs:
    - targets:
      - localhost:9091
  - job_name: push-gateway-node1
    metrics_path: /metrics
    honor_labels: true
    scheme: http
    static_configs:
    - targets:
      - 10.2.10.182:9091
  - job_name: push-gateway-node2
    metrics_path: /metrics
    honor_labels: true
    scheme: http
    static_configs:
    - targets:
      - 10.2.7.244:9091
  - job_name: push-gateway-node3
    metrics_path: /metrics
    honor_labels: true
    scheme: http
    static_configs:
    - targets:
      - 10.2.10.208:9091